-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "b" INTEGER NOT NULL DEFAULT 127,
ADD COLUMN     "cover" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "g" INTEGER NOT NULL DEFAULT 127,
ADD COLUMN     "r" INTEGER NOT NULL DEFAULT 127;
